### ISSUE TITLE
Have unified documentation output

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-cli#112]
The top part of `man zonemaster-cli` (options) is more or less identical to `zonemaster-cli --help`, but not completely:

* They are presented in different ways.
* `man` is in English only, `--help` is partly translated.
* Some options are mentioned in `help` only, such as `--config` and `--sourceaddr`.

Make those to be identical by just defining it once. In the implementation the man page comes from the script `zonemaster-cli` and the help comes from CLI.pm.

The is an option `--usage` which gives the same as `--help`. Confusing.

**Comment by mattias-p** [comment]
This seems to overlap partially with #68. Can you take another look and update the one or both issues to remove the overlap?

**Comment by matsduf** [comment]
The description in this issue has been copied to #68. This issue can thus be closed.
