### ISSUE TITLE
Update installation instructions for CLI for CentOS 8

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-cli#117]
CentOS 8 is a new OS planned to be supported by release v2019.2. The installation instructions probably need to be adjusted for CentOS 8. There could be more binary packages available, but there could also be other changes.

**Comment by mattias-p** [comment]
perl-Moosex-Getopt is available on CentOS 7 but not on CentOS 8. Otherwise they seem to agree.

**Comment by matsduf** [comment]
Is it too early to support CentOS 8?

**Comment by matsduf** [comment]
Fixed by #119.
