### ISSUE TITLE
Nagios mode

### ISSUE THREAD

**Issue by pawal** [zonemaster/zonemaster-cli#125]
Add a Nagios mode to zonemaster-cli, where a user defined log level generates the different Nagios return codes. This makes it easy to use Zonemaster as a Nagios plugin.

**Comment by pawal** [comment]
No, I wrote this as a standalone application a long time ago. Feel free to reuse parts of the code.

**Comment by ser** [comment]
I would love to have nagios output in cli either. Please reopen and add these few lines <3

**Comment by matsduf** [comment]
@ser, I'm sorry, we have neither competence nor resources to develop and test a Nagios plugin. I am not even sure that such a plug-in should be hosted here. If anyone wants to develop a plug-in and sees the need of changes in the Zonemaster API we are willing to cooperate around that.

**Comment by dnmvisser** [comment]
Hii, I just finished a nagios plugin that wraps around `zonemaster-cli`, by using its json output: https://github.com/dnmvisser/nagios-check-zonemaster
Comments and feedback welcome.

**Comment by dnmvisser** [comment]
> @dnmvisser, nice initiative. It would be good if you could specify the clearly document that you make on the input and output of zonemaster-cli. In that way it will be easier for us to communicate with you when things are about to change. You are always welcome to suggest changes that make such integration more stable.

Ideally the script would ingest JSON that includes all the relevant information, including translations (those appear to be in the `message` field of the results). But the way to generate the required output changed over the recent versions. One of the requirement that I have for this nagios plugin is that it works on recent distros that have bundled `zonemaster-cli`, which means v1 and v5. To be complete and forward compatible I also looked at the current v6. This is what I've found:

|version|options|result|
|-|-|-|
|v6|`--json --no-raw`| valid json containing a key `results` which is a list of results, including `message` fields |
|v1 to v5|`--json --no-raw`<br>`--json --json_translate`<br>`--json --json_translate --no-raw`| valid json containing a a list of results, without `message` fields |


The only way (at least that I found) to have all versions emit structured data including `message` fields, was to use these options:

`--json_stream --json_translate`

The `json_stream` causes the output to consist of multiple JSON objects, but that was easy to parse. So the nagios plugin currently works with all versions of `zonemaster-cli`.

> I do not run Nagios, but do I understand it correctly that it takes the first line and checks the keyword before ":"? Are the following lines just comments for the reader that gets the ticket?

[More or less](https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/4/en/pluginapi.html). Apart from those guidelines it is usual for plugins to have a number of configurable options, such as the levels/amounts at which to trigger.
I can see how it would be possible to have the `zonemaster-cli` script include this functionality, but I also agree with your [previous comment](https://github.com/zonemaster/zonemaster-cli/issues/125#issuecomment-757837376) that it's probably best to have this feature somewhere else, separately.

The only issue now is that the plugin relies on `--json_translate`, which is marked as deprecated... So if that ever gets dropped then the plugin would have to be adapted. But for now I didn't want to implement different logic for different versions (it is possible but not neccessary atm).

**Comment by matsduf** [comment]
@dnmvisser, it is ambitious to support all versions of `zonemaster-cli`. Have you considered check for the version first and then set the options? With `zonemaster-cli --version` the version will be returned. I have to admit that it is not just the version, but it should not be complicated to get it right.

**Comment by dnmvisser** [comment]
> @dnmvisser, it is ambitious to support all versions of `zonemaster-cli`. Have you considered check for the version first and then set the options? With `zonemaster-cli --version` the version will be returned. I have to admit that it is not just the version, but it should not be complicated to get it right.

It is ambitious but the current plugin code does actually do that. It will break once `--json-translate` is not supported anymore, so by then I will need to add version checks, or an extra param. i think for now we're good.
