### ISSUE TITLE
Add share/nb.po

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-cli#156]
When zonemaster/zonemaster-engine#751 has been merged, and share/nb.po should be added.

**Comment by matsduf** [comment]
@repperille, can you contribute with a nb.mo file for CLI?

**Comment by matsduf** [comment]
@repperille, can you contribute with a nb.po file for CLI?

**Comment by repperille** [comment]
I have submitted a PR #161

**Comment by matsduf** [comment]
Resolved.
