### ISSUE TITLE
Check of PO files

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-cli#162]
In Zonemaster-Engine there are unit tests that checks the PO files, and that is check by Travis. It should exist in CLI too.

https://github.com/zonemaster/zonemaster-engine/blob/master/t/po-files.t

**Comment by pnax** [comment]
I'll do it once https://github.com/zonemaster/zonemaster-engine/pull/1195 is approved.

**Comment by pnax** [comment]
Done with #314
