### ISSUE TITLE
Version of Zonemaster::LDNS

### ISSUE THREAD

**Issue by pawal** [zonemaster/zonemaster-cli#181]
The CLI --version does not show which version of Zonemaster::LDNS is being used. Which is more important than Module versions, since they are all included in the specific Engine version.

```
$ zonemaster-cli --version
CLI version:    v3.0.1
Engine version: v4.0.3

Test module versions:
        Address: v1.0.8
        Basic: v1.0.15
        Connectivity: v1.0.17
        Consistency: v1.1.15
        DNSSEC: v1.1.25
        Delegation: v1.0.19
        Nameserver: v1.0.26
        Syntax: v1.0.9
        Zone: v1.0.14
```

**Comment by matsduf** [comment]
It is a good suggestion to add the version of Zonemaster::LDNS, and that should not be too complicated. @pawal, do you suggest to remove the module versions, or do you think they should be kept?

**Comment by pawal** [comment]
I personally don't see a use from them, don't know what others think. There is no clear use-case for it to be included as I see it.

**Comment by pnax** [comment]
Done in #306
