### ISSUE TITLE
Problem installing Net::Interface on CentOS 8

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-cli#187]
I'm having trouble installing Net::Interface on CentOS 8. It's not an error in Zonemaster but it is a problem for us. This is what I get. Here's the end of the output. I'm also attaching the full output: [output.txt](https://github.com/zonemaster/zonemaster-cli/files/5842984/output.txt).

```
$ sudo cpanm Net::Interface

... SNIP ...

checking for size_t... yes
checking for int8_t... yes
checking for int16_t... yes
checking for int32_t... yes
checking for int64_t... yes
checking for uint8_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for caddr_t... yes
checking for memcmp... yes
checking for memset... yes
checking for memcpy... yes
checking for bzero... yes
checking for getpagesize... yes
checking for memmove... yes
checking for getnameinfo... yes
checking whether byte ordering is bigendian... no
checking for uint8_t... yes
checking size of uint8_t... configure: error: cannot compute sizeof (uint8_t)
See `config.log' for more details.
could not open config.h
N/A
! Configure failed for Net-Interface-1.016. See /root/.cpanm/work/1611145868.28244/build.log for details.
```

Do you guys have CentOS 8 installations where you can try to reproduce this? I hope this is a problem on my end, but I don't think it is.

**Comment by matsduf** [comment]
I do not have any CentOS 8 system, but I could possibly set one up. Does it work in CentOS 7?

**Comment by matsduf** [comment]
https://stackoverflow.com/questions/61597959/compiling-perl-netinterface-module-on-centos-8-1-fails

**Comment by mattias-p** [comment]
On CentOS 7 `sudo cpanm Net::Interface` works without problem.

The SO thread helped me get further. Thanks! (I wonder how I missed it in my own searches)

Anyway, the --enable-shared parameter doesn't seem to make a difference, but running ./configure before perl Makefile.PL does! If ./configure hasn't been run already Makefile.PL will run it, but it includes a boat load of options. One or more of those options must be tripping me up. I'll try to figure out which one.

**Comment by mattias-p** [comment]
I found the culprit. It's the `-specs=/usr/lib/rpm/redhat/redhat-hardened-ld` argument provided to ./configure under LDFLAGS. Now, if I only know how to override it and what to override it with.. In the mean time I guess I'll go with curl+tar+configure+friends instead of cpanm for Net::Interface.

@pnax You don't happen to know your way around these parts?

**Comment by matsduf** [comment]
A work-around is included in #188

**Comment by matsduf** [comment]
@mattias-p, can this be closed?

**Comment by mattias-p** [comment]
Yes.
