### ISSUE TITLE
Update French translation (CLI)

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-cli#201]
A few strings have been updated since last translation and it requires that the translation is updated. There is no special translation instructions from Zonemaster-CLI, but the [Engine Instructions for translators] can be followed if all case of "zonemaster-engine" is replaced by "zonemaster-cli". And the  [translation steps] in the document can be followed for zonemaster-cli.

[Engine Instructions for translators]: https://github.com/zonemaster/zonemaster-engine/blob/develop/docs/Translation-translators.md
[translation steps]: https://github.com/zonemaster/zonemaster-engine/blob/develop/docs/Translation-translators.md#translation-steps

**Comment by pnax** [comment]
Fixed by #204
