### ISSUE TITLE
Installing the dependencies failed: Module 'Net::Interface' is not installed

### ISSUE THREAD

**Issue by DragonLeo188** [zonemaster/zonemaster-cli#211]
I followed the instruction on installing ``zonemaster-cli``  and i got the following error:

```
(perl-venv) [dleo@localhost Net-Interface-1.016]$ sudo cpanm Zonemaster::CLI
--> Working on Zonemaster::CLI
Fetching http://www.cpan.org/authors/id/Z/ZN/ZNMSTR/Zonemaster-CLI-v3.1.0.tar.gz ... OK
Configuring Zonemaster-CLI-3.001000 ... OK
==> Found dependencies: Net::Interface
--> Working on Net::Interface
Fetching http://www.cpan.org/authors/id/M/MI/MIKER/Net-Interface-1.016.tar.gz ... OK
Configuring Net-Interface-1.016 ... N/A
! Configure failed for Net-Interface-1.016. See /root/.cpanm/work/1623297903.107660/build.log for details.
! Installing the dependencies failed: Module 'Net::Interface' is not installed
! Bailing out the installation for Zonemaster-CLI-3.001000.
```

From the above error I assume that ``Net::Interface`` is not installed so I try to install the module manually

```
(perl-venv) [dleo@localhost Net-Interface-1.016]$ cpan install Net::Interface
Loading internal logger. Log::Log4perl recommended for better logging
Reading '/home/dleo/.local/share/.cpan/Metadata'
  Database was generated on Thu, 10 Jun 2021 02:29:03 GMT
CPAN: Module::CoreList loaded ok (v5.20181130)
Net::Interface is up to date (1.016).
```

However ``Net::Interface`` is installed and the installation can't find it.

How to fix this error ?

**Comment by DragonLeo188** [comment]
I do the installation again but this time with ```sudo``` on every commands and change ``./configure`` to ``./configure --enable-shared``.

After that everything work fine and ``Zonemaster-CLI`` is installed.

**Comment by matsduf** [comment]
@DragonLeo188, I cannot see on what OS that you installed on, but Net::Interface should be included in the dependency specification in the [Installation] instruction for CLI. Is your OS one of the supported? Did you follow the instructions? Do you have suggestions for improvements of the instructions?

[Installation]: https://github.com/zonemaster/zonemaster-cli/blob/master/docs/Installation.md
