### ISSUE TITLE
Translation for Norwegian (CLI)

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-cli#226]
There is one message that needs update. Can you provide it in a comment here or a pull request?

```
msgid ""
"Source IP address used to send queries. Setting an IP address not correctly "
"configured on a local network interface causes cryptic error messages."
msgstr ""
```

**Comment by repperille** [comment]
Fra-IP-adresse brukt til å sende spørringer. Ved å bruke en IP-adresse som ikke er korrekt satt opp på et lokalt nett foråsakes kryptiske feilmeldinger.

**Comment by repperille** [comment]
I am working with the rest of the translations related to #1006, but they will come later...

**Comment by matsduf** [comment]
> Fra-IP-adresse brukt til å sende spørringer. Ved å bruke en IP-adresse som ikke er korrekt satt opp på et lokalt nett forårsakes kryptiske feilmeldinger.

PR #228 created.

**Comment by matsduf** [comment]
> I am working with the rest of the translations related to #1006, but they will come later in a PR...

To clarify, zonemaster/zonemaster-engine#1006

**Comment by matsduf** [comment]
Resolved by #228
