### ISSUE TITLE
--json do not result in --nstimes be in JSON

### ISSUE THREAD

**Issue by patrikhson** [zonemaster/zonemaster-cli#245]
Even if --json is given as argument, the table with response times of name servers that is given as part of the result with --nstimes (or --elapsed) is in text format and not JSON.

```
$ docker run -t --rm zonemaster/cli netnod.se --no-progress --json --no-ipv6 --nstimes --elapsed

                              Server  Max (ms)      Min      Avg   Stddev   Median     Total
====================================  ======== ======== ======== ======== ======== =========
        nna.netnod.se/194.58.192.133      7.98     3.04     3.47     0.79     3.35    121.46
  nna.netnod.se/2a01:3f1:33:8000::53      0.00     0.00     0.00     0.00     0.00      0.00
        nnb.netnod.se/194.58.193.133     26.34    12.49    14.05     2.32    13.55    435.42
 nnb.netnod.se/2a01:3f1:433:8000::53      0.00     0.00     0.00     0.00     0.00      0.00
        nnp.netnod.se/194.58.198.133     18.70     3.13     4.14     2.83     3.32    128.49
nnp.netnod.se/2a01:3f1:3033:8000::53      0.00     0.00     0.00     0.00     0.00      0.00
        nnu.netnod.se/185.42.137.133     25.11    12.53    14.45     2.10    14.15    505.85
 nnu.netnod.se/2a01:3f0:400:8000::33      0.00     0.00     0.00     0.00     0.00      0.00
Total test run time: 14.1 seconds.
[{"args":{"algo_descr":"RSA/SHA-256","algo_num":8,"keysize":1280,"keysizemax":4096,"keysizemin":512,"keysizerec":2048,"keytag":18669},"level":"WARNING","module":"DNSSEC","tag":"DNSKEY_SMALLER_THAN_REC","testcase":"DNSSEC14","timestamp":11.823086977005},{"args":{"mname":"master.netnod.se","ns_list":"nna.netnod.se;nnb.netnod.se;nnp.netnod.se;nnu.netnod.se"},"level":"NOTICE","module":"ZONE","tag":"MNAME_NOT_IN_GLUE","testcase":"ZONE01","timestamp":13.2600109577179},{"args":{"refresh":7200,"required_refresh":14400},"level":"NOTICE","module":"ZONE","tag":"REFRESH_MINIMUM_VALUE_LOWER","testcase":"ZONE02","timestamp":13.26411485672},{"args":{"required_retry":3600,"retry":1800},"level":"NOTICE","module":"ZONE","tag":"RETRY_MINIMUM_VALUE_LOWER","testcase":"ZONE04","timestamp":13.2712020874023}]
```

**Comment by matsduf** [comment]
Based on the current implementation, then documentation is misleading. Only the results from the test cases are put into the JSON. It would be possible to change the output to include the "nstimes" table at the price of creating a breaking change of the output.

Do you have a use case for running with "nstimes" and JSON or is this just a one time run?

**Comment by patrikhson** [comment]
On 7 Jan 2022, at 15:40, Mats Dufberg wrote:

> Based on the current implementation, then documentation is misleading. Only the results from the test cases are put into the JSON. It would be possible to change the output to include the "nstimes" table at the price of creating a breaking change of the output.
>
> Do you have a use case for running with "nstimes" and JSON or is this just a one time run?

We are looking into including zone master in the Netnod service Robust Tjänst, and for that it would be interesting to display data such as:

1. Same human readable strings in the Robust Tjänst interface as in Zonemaster interface (that's why a different issue ask for human readable strings as part of the JSON)

2. The time it took to make the test, what the response time was for the various name servers etc

That said, (1) is much more interesting than (2). As it is for now, I will not include the time it took to run zonemaster tests in the robust tjänst inclusion of DNS tests.

   Patrik

**Comment by matsduf** [comment]
With Zonemaster-Backend you get an RPC-API interface to Zonemaster. Tests are stored in a database and can be retrieved. Maybe you have already considered that and come to the conclusion that Zonemaster-CLI better meets your requirements.

**Comment by patrikhson** [comment]
On 7 Jan 2022, at 16:46, Mats Dufberg wrote:

> With Zonemaster-Backend you get an RPC-API interface to Zonemaster. Tests are stored in a database and can be retrieved. Maybe you have already considered that and come to the conclusion that Zonemaster-CLI better meets your requirements.

Well...yes and no. I have been thinking about that, but did fall into the rabbit hole of being interested in running with a different "test-config-file", i.e. different settings for the levels for WARNING, ERROR etc, together with our own environment to run pods for the actual testing in our environment, so I never came back to use that idea.

At *this* point in time I feel the best is if we run zonemaster-cli with our settings, but we can also (and will most certainly) defer to zone master website for "if you have further questions, go here" (as well as possibly to dnswiz etc).

I.e. the goal of Robust Tjänst is to find _minimal_ requirements ("you have to be this tall to participate"), and then focus on give the developer or whoever on documentation on how to solve whatever problems there might be.

Not much different from Zonemaster, but definitely different from many others where it is darn difficult to get A+, or 100% or such. And they have limited if any documentation.

We just want to find the very bad errors. We do not care if there might be more things to do do become "perfect".

   Patrik

**Comment by matsduf** [comment]
> Well...yes and no. I have been thinking about that, but did fall into the rabbit hole of being interested in running with a different "test-config-file", i.e. different settings for the levels for WARNING, ERROR etc, together with our own environment to run pods for the actual testing in our environment, so I never came back to use that idea.

If you run your own Zonemaster-Backend you can have your own profiles and select different profiles for different tests. That would be the same profiles as you can use with Zonemaster-CLI.

Zonemaster-Backend does not require using a GUI. There is a tool `zmb` included in the installation which is a command line interface to the RPC-API.

There are differences between the two, but the testing is done in the same way.

**Comment by patrikhson** [comment]
On 7 Jan 2022, at 17:10, Mats Dufberg wrote:

> If you run your own Zonemaster-Backend you can have your own profiles and select different profiles for different tests. That would be the same profiles as you can use with Zonemaster-CLI.

Can that be run standalone in a container, like (now) zone-master-cli?

I.e. we like being able to run tests in a pod, and then the pod dies. So absolutely zero state is left after a test (and it is also easy to handle load balancing with orchestration). I understand if you have a central "backend" that can do queuing by itself, and then clients requesting tests, but our overall design is different.

I am happy to explain more of our design if you want.

For more info, see <https://github.com/Netnod/robust-tjanst>. Note though that the branch paf-zonemaster is based on the old pawal version of zone master docker image. This is what I am working on now. And also the old interface between the Robust Tjänst core and the various tests. We changed the interface the last thing we did before x-mas.

   Patrik

**Comment by matsduf** [comment]
> Can that be run standalone in a container, like (now) zone-master-cli? 
> 
> I.e. we like being able to run tests in a pod, and then the pod dies. So absolutely zero state is left after a test (and it is also easy to handle load balancing with orchestration).

We have not created any image for Zonemaster-Backend, but it would be possible to run dockerized.

It is possible to run the Backend in a small VPS on your laptop. Backend runs 2-3 daemons. One daemon is the RPC-API, which will listen to requests on some TCP port. The second daemon is the test agent, that executes the tests. The two daemons communicate via the database. The RPC-API daemon creates the tests in the database and the test agent picks it up and executes it. And delivers the result in the database, where the RPC-API daemon can fetch the result. A lightweight solution is to use SQLite as database, and then the two daemons must run in the same machine (container or VPS). A solution that can take heavier load uses MariaDB (MySQL) or PostgreSQL as database, which would then be a third daemon. In a default installation all three daemons run on the same machine, but they could also be spread to different machines (containers).

You can call me if you have more questions or want to discuss this.
