### ISSUE TITLE
--no-raw and --json together does not give expected result

### ISSUE THREAD

**Issue by patrikhson** [zonemaster/zonemaster-cli#246]
Regardless of whether --no-raw or --raw is mixed with --json, the same result is given back. It would be more interesting if the human readable result is included in the JSON if --no-raw is included as argument (i.e. in JSON you can mix raw and non-raw output). 

My goal, what I wanted, was to get the human readable information also in JSON format in some way.

```
$ docker run -t --rm zonemaster/cli netnod.se --no-ipv6 --json --raw
[{"args":{"algo_descr":"RSA/SHA-256","algo_num":8,"keysize":1280,"keysizemax":4096,"keysizemin":512,"keysizerec":2048,"keytag":18669},"level":"WARNING","module":"DNSSEC","tag":"DNSKEY_SMALLER_THAN_REC","testcase":"DNSSEC14","timestamp":11.6931550502777},{"args":{"mname":"master.netnod.se","ns_list":"nna.netnod.se;nnb.netnod.se;nnp.netnod.se;nnu.netnod.se"},"level":"NOTICE","module":"ZONE","tag":"MNAME_NOT_IN_GLUE","testcase":"ZONE01","timestamp":13.1522798538208},{"args":{"refresh":7200,"required_refresh":14400},"level":"NOTICE","module":"ZONE","tag":"REFRESH_MINIMUM_VALUE_LOWER","testcase":"ZONE02","timestamp":13.156800031662},{"args":{"required_retry":3600,"retry":1800},"level":"NOTICE","module":"ZONE","tag":"RETRY_MINIMUM_VALUE_LOWER","testcase":"ZONE04","timestamp":13.1641368865967}]
$ docker run -t --rm zonemaster/cli netnod.se --no-ipv6 --json --no-raw
[{"args":{"algo_descr":"RSA/SHA-256","algo_num":8,"keysize":1280,"keysizemax":4096,"keysizemin":512,"keysizerec":2048,"keytag":18669},"level":"WARNING","module":"DNSSEC","tag":"DNSKEY_SMALLER_THAN_REC","testcase":"DNSSEC14","timestamp":11.8387558460236},{"args":{"mname":"master.netnod.se","ns_list":"nna.netnod.se;nnb.netnod.se;nnp.netnod.se;nnu.netnod.se"},"level":"NOTICE","module":"ZONE","tag":"MNAME_NOT_IN_GLUE","testcase":"ZONE01","timestamp":13.2705669403076},{"args":{"refresh":7200,"required_refresh":14400},"level":"NOTICE","module":"ZONE","tag":"REFRESH_MINIMUM_VALUE_LOWER","testcase":"ZONE02","timestamp":13.2746179103851},{"args":{"required_retry":3600,"retry":1800},"level":"NOTICE","module":"ZONE","tag":"RETRY_MINIMUM_VALUE_LOWER","testcase":"ZONE04","timestamp":13.2826919555664}]

```

**Comment by patrikhson** [comment]
On 7 Jan 2022, at 16:00, Mats Dufberg wrote:

> The documentation is misleading. "raw" and "json" cannot be combined. There are three different output formats of the test case results, normal, raw and json. The implementation should not accept both.
>
> I think it should be possible to add the message ID (human language) to the JSON output. The message ID could either be fully expanded with the arguments or with the arguments by name. From the JSON result of netnode.se I get (among others)
>
> ```json
>   {
>     "args": {
>       "refresh": 7200,
>       "required_refresh": 14400
>     },
>     "level": "NOTICE",
>     "module": "ZONE",
>     "tag": "REFRESH_MINIMUM_VALUE_LOWER",
>     "testcase": "ZONE02",
>     "timestamp": 12.4104640483856
>   }
> ```
>
> The addition data could then be either
> ```
> "message": "SOA 'refresh' value (7200) is less than the recommended one (14400)."
> ```
> or
> ```
> "message": "SOA 'refresh' value ({refresh}) is less than the recommended one ({required_refresh})."
> ```
>
> Hopefully translation can also be supported.
>
> Would such an update meet what you expected or wanted?

Yes. The first of the two would be the best so I do not have to re-parse the data in the "message" slot.

   Patrik

**Comment by matsduf** [comment]
Actually, the following command might meet your request already:

```
zonemaster-cli netnod.se --json_stream --json_translate | jq
```
(...)
```json
{
  "args": {
    "refresh": 7200,
    "required_refresh": 14400
  },
  "level": "NOTICE",
  "message": "SOA 'refresh' value (7200) is less than the recommended one (14400).",
  "module": "ZONE",
  "tag": "REFRESH_MINIMUM_VALUE_LOWER",
  "testcase": "ZONE02",
  "timestamp": 12.457995891571
}
```

**Comment by matsduf** [comment]
```
zonemaster-cli netnod.se --json_stream --json_translate --locale sv_SE.UTF-8| jq
```
(...)
```json
{
  "args": {
    "refresh": 7200,
    "required_refresh": 14400
  },
  "level": "NOTICE",
  "message": "SOA-postens 'refresh'-värde (7200) är lägre än rekommenderat (14400).",
  "module": "ZONE",
  "tag": "REFRESH_MINIMUM_VALUE_LOWER",
  "testcase": "ZONE02",
  "timestamp": 12.1978390216827
}
```

**Comment by patrikhson** [comment]
On 7 Jan 2022, at 16:08, Mats Dufberg wrote:

> Actually, the following command might meet your request already:

:-) Good catch!

  Patrik

**Comment by patrikhson** [comment]
On 7 Jan 2022, at 16:09, Mats Dufberg wrote:

> ```
> zonemaster-cli netnod.se --json_stream --json_translate --locale sv_SE.UTF-8| jq

Ohhh....tne one might want to use multiple locale and get multiple message strings? :-)

Maybe I should drop the keyboard and make dinner now?

Have a nice weekend!

   Patrik

**Comment by matsduf** [comment]
Take a look at Zonemaster-Backend. Then you can run the test and fetch the result -- the same result -- in different translations. One translation at a time, but with no delay of re-testing.

**Comment by patrikhson** [comment]
This did the trick for me.

Thanks!

   Patrik

**Comment by matsduf** [comment]
I take it that I can close this issue. Issue #247 has been opened to fix how the combination of options are handled and documented.
