### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by bortzmeyer** [zonemaster/zonemaster-cli#249]
In `zonemaster-cli/blob/master/docs/Installation.md#installation-on-debian`:

```
sudo cpanm Zonemaster::CLI
```

Should be `cpan`.

**Comment by matsduf** [comment]
In https://github.com/zonemaster/zonemaster-cli/blob/master/docs/Installation.md#Installation-on-Debian it says


1) Add Zonemaster packages repository to repository list
   ```sh
   curl -LOs https://package.zonemaster.net/setup.sh
   sudo sh setup.sh
   ```
2) Install Zonemaster CLI
   ```sh
   sudo apt install zonemaster-cli
   ```
3) Update configuration of "locale"


Else, in all places where installation is done from CPAN, `cpanm` is used. `cpanm` is installed before Zonemaster-LDNS and Zonemaster-Engine is installed from CPAN.

**Comment by mattias-p** [comment]
It could be noted that `cpanm` is the recommended way of installing CPAN modules. See https://www.cpan.org/modules/INSTALL.html.
