### ISSUE TITLE
Installation failed on Ubuntu

### ISSUE THREAD

**Issue by bortzmeyer** [zonemaster/zonemaster-cli#250]
Following ` https://github.com/zonemaster/zonemaster-cli/blob/master/docs/Installation.md#Installation-on-Ubuntu`:

```
% sudo cpan Zonemaster::CLI  
...
#     Error:  Can't locate Zonemaster/Engine.pm in @INC (you may need to install the Zonemaster::Engine module) (@INC contains: /root/.local/share/.cpan/build/Zonemaster-CLI-v3.2.0-0/inc /root/.local/share/.cpan/build/Zonemaster-CLI-v3.2.0-0/blib/lib /root/.local/share/.cpan/build/Zonemaster-CLI-v3.2.0-0/blib/arch /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /root/.local/share/.cpan/build/Zonemaster-CLI-v3.2.0-0/blib/lib/Zonemaster/CLI.pm line 20.
# BEGIN failed--compilation aborted at /root/.local/share/.cpan/build/Zonemaster-CLI-v3.2.0-0/blib/lib/Zonemaster/CLI.pm line 20.
# Compilation failed in require at t/00-load.t line 9.
# BEGIN failed--compilation aborted at t/00-load.t line 9.
Use of uninitialized value $Zonemaster::CLI::VERSION in concatenation (.) or string at t/00-load.t line 12.
# Looks like your test exited with 255 just after 1.
FAILED--Further testing stopped.
make: *** [Makefile:778: test_dynamic] Error 255
  ZNMSTR/Zonemaster-CLI-v3.2.0.tar.gz
2 dependencies missing (Zonemaster::Engine,Zonemaster::LDNS); additionally test harness failed
  /usr/bin/make test -- NOT OK
//hint// to see the cpan-testers results for installing this module, try:
  reports ZNMSTR/Zonemaster-CLI-v3.2.0.tar.gz
```

Installing Zonemaster::LDNS fails:

```
Can't link/include C library 'idna.h', 'idn', aborting.
No 'Makefile' created  ZNMSTR/Zonemaster-LDNS-2.2.1.tar.gz
  /usr/bin/perl Makefile.PL INSTALLDIRS=site -- NOT OK
```
Installing ` libidn2-dev`  does not help.

**Comment by matsduf** [comment]
1. Start with installing Zonemaster-LDNS and Zonemaster-Engine. You can choose to install from package or from CPAN.

https://github.com/zonemaster/zonemaster-engine/blob/master/docs/Installation.md#installation-on-debian

2. Then install Zonemaster-CLI, if you used package above, use package again. Else use CPAN.

https://github.com/zonemaster/zonemaster-cli/blob/master/docs/Installation.md#Installation-on-Debian

3. Or use Docker: https://github.com/zonemaster/zonemaster-cli/blob/master/USING.md

**Comment by blacksponge** [comment]
@bortzmeyer Which version of Ubuntu are you using ?

**Comment by blacksponge** [comment]
> Installing libidn2-dev does not help

According to the [engine installation document](https://github.com/zonemaster/zonemaster-engine/blob/master/docs/Installation.md#installation-on-ubuntu) it should be `libidn11-dev` instead . Could you retry with this one and tell be how it goes?

**Comment by bortzmeyer** [comment]
> @bortzmeyer Which version of Ubuntu are you using ?

LinuxMint 20.2 (an Ubuntu derivative). But a regular Ubuntu 20.04 has exactly the same problem.

**Comment by matsduf** [comment]
> LinuxMint 20.2 (an Ubuntu derivative). But a regular Ubuntu 20.04 has exactly the same problem.

The steps that you showed in the description did not follow the steps in the installation instruction. If you follow those, do you still get the problem? Could you show what it says then? Start with Zonemaster-Engine, and then Zonemaster-CLI.

**Comment by bortzmeyer** [comment]
OK, in the end, the problem is that the list of dependencies is incomplete. In the line after 'Installation on Ubuntu \  Install dependencies:', you have to add at the end the dependencies `libidn11-dev libssl-dev`. After that, the rest works.

**Comment by matsduf** [comment]
If this issue still remains then more information must be provided.
