### ISSUE TITLE
Make translation to Danish complete (CLI)

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-cli#61]
Translation to Danish is beeing added to Engine (https://github.com/dotse/zonemaster-engine/pull/354). Translation is needed in CLI too.

There is now a share/da.po, but that is only a placeholder with English translation. That must be translated to Danish.

**Comment by matsduf** [comment]
@haarbo, please refer to this issue for translation in CLI.

**Comment by sandoche2k** [comment]
@haarbo Will it be possible to do the Danish translation for the file share/da.po?

**Comment by matsduf** [comment]
@haarbo, do you have time to contribute?

**Comment by haarbo** [comment]
Hello Mats

Yes, I will find time.

I am not especially home in using Git(Hub) – is it possible you could help me fetching the relevant files that needs translation?

Or maybe point me in the right direction?


Med venlig hilsen

Niels Haarbo
Seniorkonsulent / Senior Consultant
[DK                      Hostmaster]<http://www.dk-hostmaster.dk/>
DK Hostmaster A/S
Ørestads Boulevard 108, 11. sal
DK-2300 København S

+45 3364 6050 • haarbo@dk-hostmaster.dk<mailto:haarbo@dk-hostmaster.dk> • www.dk-hostmaster.dk<http://www.dk-hostmaster.dk/>
This is an email from DIFO/DK Hostmaster A/S. This message may contain confidential information and is intended solely for the use of the intended addressee. If you are not the intended addressee, please notify the sender immediately and delete this e-mail from your system.

**Comment by matsduf** [comment]
@haarbo, thank your for helping us. 

There are two options. The preferred option is that you edit [da-po] in Github and make a pull request. Make the pull request against the develop branch.

The other option is that you download [da-po], edit it locally and then attach is in a reply to this issue. (When you write a reply, click on "attach files" on the bar to the small window that you write in.)

The fallback is that you send the updated file as an email to me.

[da-po]: https://github.com/zonemaster/zonemaster-cli/blob/master/share/da.po

**Comment by matsduf** [comment]
PR #109 will resolve this issue.

**Comment by matsduf** [comment]
Resolved by #109.
