### ISSUE TITLE
Case in-sentitive --level parameter

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-cli#74]
Zonemaster CLI should perform case folding of its CLI arguments where reasonable. Today the --level parameter is case sensitive. In the following example, only the first command is accepted. Both should be accepted and they should be equivalent.

    zonemaster-cli --level INFO zonemaster.net
    zonemaster-cli --level info zonemaster.net

**Comment by matsduf** [comment]
Good suggestion!
