### ISSUE TITLE
Print diagnostics to STDERR

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-cli#77]
The `--config` and `--policy` parameters print diagnostic information about what file was loaded (e.g. "Loading policy from myfile.json"). Today these diagnostics are printed to STDOUT. This behavior is problematic when the output is fed to `jq` for pretty printing. The diagnostics should be printed to STDERR instead in order to keep them separated from the normal output.

**Comment by matsduf** [comment]
PR #84 has been created.

**Comment by mattias-p** [comment]
PR #84 solved some aspects of this issue, but it did not resolve the problem with regard to the `--json_stream` option.

**Comment by mattias-p** [comment]
Fixed in #85.
